// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensoreApp.Data;

#nullable disable

namespace SensoreApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensoreApp.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("New");

                    b.Property<decimal>("ThresholdPct")
                        .HasColumnType("decimal(5,2)");

                    b.Property<float>("TriggerValue")
                        .HasColumnType("real");

                    b.Property<int>("TriggeringFrameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SensoreApp.Models.FrameMetric", b =>
                {
                    b.Property<int>("FrameMetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrameMetricID"));

                    b.Property<decimal>("COV")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ContactAreaPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FrameID")
                        .HasColumnType("int");

                    b.Property<decimal>("PeakPressureIndex")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("FrameMetricID");

                    b.ToTable("FrameMetrics");
                });

            modelBuilder.Entity("SensoreApp.Models.PatientClinician", b =>
                {
                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("ClinicianID")
                        .HasColumnType("int");

                    b.HasKey("PatientID", "ClinicianID");

                    b.HasIndex("ClinicianID");

                    b.ToTable("PatientClinicians");
                });

            modelBuilder.Entity("SensoreApp.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime?>("ComparisonDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ComparisonDateTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportFrame", b =>
                {
                    b.Property<int>("ReportFrameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportFrameID"));

                    b.Property<int>("FrameID")
                        .HasColumnType("int");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("ReportFrameID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportFrames");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportMetric", b =>
                {
                    b.Property<int>("ReportMetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportMetricID"));

                    b.Property<decimal?>("ComparisonValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("ReportMetricID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportMetrics");
                });

            modelBuilder.Entity("SensoreApp.Models.SensorDevices", b =>
                {
                    b.Property<int>("SensorDeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorDeviceID"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SensorDeviceID");

                    b.ToTable("SensorDevices");
                });

            modelBuilder.Entity("SensoreApp.Models.ThresholdSettings", b =>
                {
                    b.Property<int>("ThresholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThresholdID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ThresholdID");

                    b.HasIndex("UserID");

                    b.ToTable("ThresholdSettings");
                });

            modelBuilder.Entity("SensoreApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SensoreApp.Models.Clinician", b =>
                {
                    b.HasBaseType("SensoreApp.Models.User");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue("Clinician");
                });

            modelBuilder.Entity("SensoreApp.Models.Patient", b =>
                {
                    b.HasBaseType("SensoreApp.Models.User");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("SensoreApp.Models.Alert", b =>
                {
                    b.HasOne("SensoreApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SensoreApp.Models.PatientClinician", b =>
                {
                    b.HasOne("SensoreApp.Models.Clinician", "Clinician")
                        .WithMany("PatientClinicians")
                        .HasForeignKey("ClinicianID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SensoreApp.Models.Patient", "Patient")
                        .WithMany("PatientClinicians")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SensoreApp.Models.Report", b =>
                {
                    b.HasOne("SensoreApp.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SensoreApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportFrame", b =>
                {
                    b.HasOne("SensoreApp.Models.Report", "Report")
                        .WithMany("ReportFrame")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportMetric", b =>
                {
                    b.HasOne("SensoreApp.Models.Report", "Report")
                        .WithMany("ReportMetric")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SensoreApp.Models.ThresholdSettings", b =>
                {
                    b.HasOne("SensoreApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SensoreApp.Models.Report", b =>
                {
                    b.Navigation("ReportFrame");

                    b.Navigation("ReportMetric");
                });

            modelBuilder.Entity("SensoreApp.Models.Clinician", b =>
                {
                    b.Navigation("PatientClinicians");
                });

            modelBuilder.Entity("SensoreApp.Models.Patient", b =>
                {
                    b.Navigation("PatientClinicians");
                });
#pragma warning restore 612, 618
        }
    }
}
