// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensoreApp.Data;

#nullable disable

namespace SensoreApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensoreApp.Models.FrameMetric", b =>
                {
                    b.Property<int>("FrameMetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrameMetricID"));

                    b.Property<decimal>("COV")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ContactAreaPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FrameID")
                        .HasColumnType("int");

                    b.Property<decimal>("PeakPressureIndex")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("FrameMetricID");

                    b.ToTable("FrameMetrics");
                });

            modelBuilder.Entity("SensoreApp.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime?>("ComparisonDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ComparisonDateTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportFrame", b =>
                {
                    b.Property<int>("ReportFrameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportFrameID"));

                    b.Property<int>("FrameID")
                        .HasColumnType("int");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("ReportFrameID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportFrames");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportMetric", b =>
                {
                    b.Property<int>("ReportMetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportMetricID"));

                    b.Property<decimal?>("ComparisonValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("ReportMetricID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportMetrics");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportFrame", b =>
                {
                    b.HasOne("SensoreApp.Models.Report", "Report")
                        .WithMany("ReportFrame")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SensoreApp.Models.ReportMetric", b =>
                {
                    b.HasOne("SensoreApp.Models.Report", "Report")
                        .WithMany("ReportMetric")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SensoreApp.Models.Report", b =>
                {
                    b.Navigation("ReportFrame");

                    b.Navigation("ReportMetric");
                });
#pragma warning restore 612, 618
        }
    }
}
